---
title: "compare-commmutes-lm"
author: "Jenna Krall"
date: "2/25/2022"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
# libraries
library(dplyr)

library(tidyverse)
library(knitr)
library(here)
library(ggthemes)
library(RColorBrewer)
library(forcats)
library(lubridate)


library(broom.mixed)
# add here to fixfile path
# need raster package
library(raster)

library(dplyr)
library(nlme)

```

```{r}
load(here("data/comparedat.RData"))
load(here("data/rcomm2.RData"))
load(here("data/iqrs.RData"))
load(here("data/commute-loc.RData"))
load(here("data/vah.RData"))
load(here("data/va24.RData"))


# get functions for models
source(here("functions/model-funs.R"))

figloc <- "~/Dropbox/CommuteVar/figures/"
```



```{r}
# get day1/day2 info
days <- mutate(coms2, date_local = date(rdatetime)) %>%
               dplyr::select(date_local, min2, commute, ID) %>% unique()


hours <- group_by(coms2, commute, ID, min2) %>%
  mutate(mindate = min(rdatetime), time_local = hour(mindate),
         date_local= date(rdatetime)) %>%
  ungroup() %>%
  dplyr::select(commute, ID, min2, date_local, time_local) %>%
  unique() %>%
  left_join(., vah0) %>%
  dplyr::select(commute, ID, min2, obsdiff) %>%
  pivot_wider(names_from = "min2", values_from = "obsdiff") %>%
  mutate(obsdiff = second - first) %>%
  dplyr::select(-c(second, first))

dayPM <- left_join(days, va24) %>%
  dplyr::select(-date_local) %>%
  pivot_wider(names_from = "min2", values_from = "daily") %>%
  mutate(daily = second - first) %>%
  dplyr::select(-c(second, first))


# get speed
sp <- dplyr::select(rcomm2, ID, rdatetime, mph, date) %>%
  unique() %>%
  left_join(coms2, .) %>%
  group_by(commute, ID, min2) %>%
  summarize(mph = mean(mph, na.rm = T)) %>%
  pivot_wider(names_from = "min2",values_from = "mph") %>%
  mutate(mph = second - first) %>%
  dplyr::select(-c(second, first))

# get weather

cweath <- dplyr::select(rcomm2, date_local, cat5sm) %>%
  unique() %>%
  left_join(days, .) %>% 
  dplyr::select(-date_local) %>%
  pivot_wider(names_from = "min2", values_from = "cat5sm") %>%
  # comb is which change, same is whether changed
  mutate(comb = paste0(second, first), cat5sm = ifelse(second == first, 1, 0)) %>%
  dplyr::select(-c(first, second, comb))




weath1 <- dplyr::select(rcomm2, date_local, awnd, prcpbin, RH, snowbin, tmax, tmin) %>% unique() %>%
  left_join(days, .) %>% 
  pivot_longer(awnd : tmin) %>%
  dplyr::select(-date_local) %>%
  pivot_wider(names_from = "min2") %>%
  mutate(diffweath = second - first) %>%
  dplyr::select(-c(first, second)) %>%
  pivot_wider(values_from = diffweath) %>%
  full_join(cweath) %>%
  full_join(hours) %>%
  full_join(dayPM) %>%
  full_join(sp)

coms3a <- dplyr::select(comspaired, -c(first, second)) %>%
  full_join(weath1) %>%
  mutate(IDcommute = paste0(ID, commute))
coms3 <- dplyr::filter(coms3a, !(ID == "GMU1001" & commute== "evening" & propcs < 6.26 & propcs >6.24))

# match propcs with time
timestart <- mutate(coms2, date = date(rdatetime)) %>%
  group_by(commute, ID, date)%>%
  mutate(start = min(rdatetime), min = as.numeric((rdatetime - start) / 60)) %>%
  ungroup()%>%
  dplyr::select(commute, ID, min2, propcs, min) %>%
  unique()

timestart1 <- filter(timestart, min2 == "first") %>% arrange(ID, commute, min)
timestart2 <- filter(timestart, min2 == "second")%>% arrange(ID, commute, min)

```




```{r}
get_lme <- function(data1, iqrs, covar, rer = "~propcs | IDcommute ",
                    re = "~1 | IDcommute ", intervals = T, corr = T) {

  # get correlation
  if(corr) {
    #
    # cs1 <- corARMA(form = formula(rer), p = 1, q = 1)
    cs1 <- corAR1(form = formula(rer))
    cs1 <- Initialize(cs1, data = data1)
  } else {
    cs1 <- NULL
  }
  # Fit model
  eqn1 <- paste0("diffPM ~", covar)
  lme1 <- lme(formula(eqn1),
              random= formula(re),
              data=data1, correlation= cs1)

  # Get residuals
  lme1b <- augment(lme1)

  # format
  t1 <- tidy(lme1, conf.int = T) %>%
    filter(effect == "fixed", term != "(Intercept)") %>%
    mutate(term = case_when(term == "snowbinL1m" ~ "snowbin",
                            term == "awndL1" ~ "awnd",
                            term == "tmaxL1" ~ "tmax",
                            term == "tminL1" ~ "tmin",
                            term == "prcpbinL1" ~ "prcpbin",
                            TRUE ~ term)) %>%
    full_join(iqrs) %>%
    mutate(IQR = ifelse(is.na(IQR), 1, IQR),
           estimateIQR = estimate * IQR,
           conf.lowIQR = conf.low * IQR,
           conf.highIQR = conf.high * IQR,
           term1 = factor(term, levels = c("daily", "obsdiff", "srness", "timemin",
                                           "rtypeLocalConn",  "rtypeLocal",    "rtypeOther",
                                           "tmax" ,"tmin",  "prcpbin", "snowbin" , "awnd", "cat5smSE", "cat5smOther",
                                           "hourly", "hourlymonth"),
                          labels = c("Daily PM2.5", "Hourly PM2.5", "Roadiness", "Time since start",
                                     "Local conn", "Local", "Other",
                                     "Max Temp",  "Min Temp", "Precipitation","Snow",
                                     "Wind", "WindDir SE", "WindDir Other", "Hour Mean", "Hour Mon Mean")),
           type = ifelse(term %in% c("daily", "obsdiff", "srness",
                                     "rtypeLocalConn",  "rtypeLocal",    "rtypeOther", "timemin"),
                         "Pollution", "Meteorology"),
           type2 = ifelse(term %in% c("prcpbin", "snowbin",
                                      "rtypeLocalConn",  "rtypeLocal",
                                      "rtypeOther", "cat5smSE",
                                      "cat5smOther"), "cat", "num")) %>%
    filter(!is.na(estimate))


  # get intervals for variance components
  if(intervals) {
    print(intervals)
    int1 <- intervals(lme1)
    reint <- int1$reStruct


    # bind together intervals
    re <- bind_rows(int1$sigma, reint[[1]][1, ])
    for(i in 2 : length(reint)) {
      re <- bind_rows(re, reint[[i]][1, ])
    }
    re <- mutate(re, name = c("sigma", names(reint))) %>%
      rename(est= `est.`)

  } else {
    sigs <- lme1$sigma

    re1 <- coef(lme1$modelStruct$reStruct, unconstrained = F) %>% sqrt()
    re1 <- re1 * sigs
    names(re1) <- strsplit(names(re1), "\\.") %>% sapply(., function(x) x[[1]])

    re1b <- c(sigs, re1)
    re <- data.frame(est = re1b, name = c("sigma", names(re1)))
    re <- mutate(re, est = as.numeric(est))
  }


  # return
  if("corStruct" %in% names(lme1$modelStruct)) {
    cor <- lme1$modelStruct$corStruct
  } else {
    cor <- NA
  }

  list(t1 = t1, re = re, cor = cor, lme1 = lme1, aug = lme1b)
}



run_all <- function(dat, covars) {
  lmeall <- list()
  for(i in 1 : length(covars)) {
    res <- get_lme(dat, iqrs, covars[i], corr = F, intervals = F)

    t1 <- res$t1
    aug <- mutate(res$aug, type = covars[i]) %>%
      rename(value = covars[i]) %>%
      dplyr::select(ID, commute, propcs, value, .resid, type)
    
    lmeall[[i]] <- res$lme1
    if(i == 1) {
      
      tall <- t1
      augall <- aug
    } else {
      tall <- bind_rows(tall, t1)
      augall <- bind_rows(augall, aug)
    }
  }

  list(augall = augall, ests = tall, lmeall = lmeall)
}

```


# Explore

```{r}
ggplot(coms3, aes(x = propcs, y = diffPM, group = IDcommute)) +
  geom_line()


scoms3 <- group_by(coms3, IDcommute) %>% summarize(md = median(diffPM))
ggplot(scoms3, aes(x = md)) + geom_boxplot()

```

# Spearman correlation

Are ties an issue?
```{r}
lm1 <- function(dat) {
  with(dat, cor(md, value, method = "spearman"))
  # res1 <- with(dat, cor.test(md, value, method = "spearman"))
  # paste0(round(res1$estimate, 2), " (", round(res1$p.value, 2), ")")
}
sc <- group_by(coms3, IDcommute) %>% mutate(adiffPM = diffPM - daily, md = median(adiffPM))  %>%
  dplyr::select(-c(propcs, diffPM, adiffPM)) %>%
  unique() 

sc %>% dplyr::select(IDcommute, prcpbin, snowbin, cat5sm, md) %>%
  pivot_longer(prcpbin : cat5sm) %>%
  group_by(name, value) %>%
  summarize(median = median(md), IQR = IQR(md)) %>%
  mutate(median = round(median, 2), IQR = round(IQR, 2),
         medianIQR = paste0(median, " (", IQR, ")")) %>%
  dplyr::select(-c(median, IQR)) %>%
  pivot_wider(names_from = "value", values_from = "medianIQR") %>%
  # only1
  dplyr::filter(name != "snowbin")

with(sc, wilcox.test(md ~ prcpbin))
with(sc, wilcox.test(md ~ cat5sm))


sc %>%  pivot_longer(awnd : mph) %>%
  nest(data = c(ID : md, value)) %>%
  mutate(cor1 = map(data, lm1)) %>%
  unnest(cor1) %>%
  dplyr::select(-data) %>%
  dplyr::filter(!(name %in% c("prcpbin", "snowbin", "cat5sm"))) %>%
  kable(digits = 2)


ggplot(sc, aes(x = mph, y =md)) + geom_point()
```


# Summarize

```{r}
coms3b <- coms3 %>% mutate(medpm = median(abs(diffPM)))


coms3b2 <- coms3b %>% dplyr::select(IDcommute, diffPM, daily) %>%
  group_by(IDcommute) %>%
  summarize(med = abs(median(diffPM)), IQR = IQR(diffPM),
            q1 = quantile(diffPM, probs = 0.25), 
                        q3 = quantile(diffPM, probs = 0.75)) %>%
  arrange(med)

coms3b2
summarize(coms3b2, median(med), min(med), max(med))

coms3c0 <- coms3 %>% dplyr::select(IDcommute, diffPM, daily) %>%
  group_by(IDcommute) %>%
  mutate(diffPM = abs(diffPM - daily), medpm = median(abs(diffPM))) 


coms3c <- coms3c0 %>%
  summarize(med = median(diffPM), IQR = IQR(diffPM),
            q1 = quantile(diffPM, probs = 0.25), 
                        q3 = quantile(diffPM, probs = 0.75))

summarize(coms3c, median(med), min(med), max(med))

coms3c %>%
  mutate(med = round(med, 2), q1 = round(q1, 2),q3 = round(q3, 2),
    MedianIQR = paste0(med, " (", q1, ", ", q3, ")")) %>%
  arrange(med) %>%
  dplyr::select(-c(med, IQR, IDcommute, q1, q3)) %>%
  rowid_to_column() %>%
  rename(ID = rowid) 

```


```{r}
coms3b <- mutate(coms3b, type = "Unadjusted")
coms3c0 <- mutate(coms3c0, type = "Adjusted")

comscom <- full_join(coms3b, coms3c0) %>%
  group_by(IDcommute) %>%
  mutate(medpm = mean(medpm))
figpaired <- ggplot(coms3b, aes(x = fct_reorder(IDcommute, medpm), y = abs(diffPM))) + geom_boxplot() +
  ylab(expression(paste("Absolute difference in PM"[2.5]," (", mu, "g/m"^3, ")", " between pairs"))) +
  xlab("Commute pairs") +
  theme_bw() +
  theme(axis.text.x = element_blank(), text = element_text(size = 12)) 


ggplot(coms3b, aes(x = fct_reorder(IDcommute, medpm), y = abs(diffPM))) + geom_boxplot() +
  ylab(expression(paste("Absolute difference in PM"[2.5]," (", mu, "g/m"^3, ")", " between pairs"))) +
  xlab("Commute pairs") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90), text = element_text(size = 12)) 



figpaired
save(figpaired, file = file.path(figloc, "figpaired.RData"))

```

Spatial information (TRI, other sources) could impact, to control, we used paired analysis.

Behavior not in control (follow cars, traffic) could impact
 
# LMM regression


## All

- When use all, there is one extreme outlier for GMU1001/evening (remove)
- No snow (only 1 different)


```{r}


res1 <- run_all(coms3, c("daily", "obsdiff", "prcpbin", "awnd", "tmax", "tmin", "RH", 
                  "cat5sm"))



ACF(res1$lmeall[[3]], resType = "normalized", maxLag = 30) %>% plot()

# check assumptions
ggplot(res1$augall, aes(x = .resid)) + geom_histogram() + facet_wrap(~type)
ggplot(filter(res1$augall, type %in% c("awnd", "daily", "obsdiff", "RH", "tmax", "tmin")), 
       aes(x = value, y = .resid)) + geom_point() + facet_wrap(~type, scales = "free")
catres <- filter(res1$augall, !(type %in% c("awnd", "daily", "obsdiff", "RH", "tmax", "tmin"))) %>%
  mutate(value = factor(value))
ggplot(catres, 
       aes(x = value, y = .resid)) + geom_boxplot() + facet_wrap(~type, scales = "free")

ggplot(res1$ests, aes(x = term, y = estimateIQR)) + 
  geom_pointrange(aes(ymin = conf.lowIQR, ymax = conf.highIQR)) +
  xlab("")+ ylab("Estimate (95% CI)") +
  geom_hline(yintercept = 0, linetype = 2, colour = "blue") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```
