---
title: 'Roadiness: analysis'
author: "Jenna Krall"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
# libraries
library(tidyverse)
library(knitr)
library(here)
library(lme4)
library(broom.mixed)
library(ggthemes)
library(nlme)
library(forcats)
library(gtools)
library(patchwork)
library(lubridate)
library(RColorBrewer)
# library(lmeInfo)

```


```{r}
# load data
load(here("data/rcomm2.RData"))


# load iqrs
load(here("data/iqrs.RData"))

# get functions for models
source(here("functions/model-funs.R"))



```



# Correlation between model components

```{r}
library(corrplot)

corr1 <- dplyr::select(rcommLM, srness1hw, srness1loc, 
                       srness500hw, srness500loc, mph, daily, obsdiff, awnd,
                       tmax, tmin, tavg, RH) %>%
  rename(RD1Hw = srness1hw, RD1Loc = srness1loc, RD500Hw = srness500hw, RD500Loc = srness500loc, 
         Speed = mph, DailyPM = daily, HourlyDevPM = obsdiff, WindSpeed = awnd, MaxTemp = tmax, MinTemp = tmin, MeanTemp = tavg, Humid = RH) %>%
  cor()
corrplot(corr1)



data.frame(corr1, var1 = rownames(corr1)) %>%
  pivot_longer(-var1) %>%
  mutate(abscor = abs(value)) %>%
  filter(abscor > 0.5 & abscor < 1) %>%
  kable(digits = 2)

ind <- upper.tri(corr1) * 1

options(knitr.kable.NA = '')
corr1b <- corr1 * ind 
corr1b[which(corr1b == 0)] <- NA
corr1b <- corr1b %>%
  data.frame() %>%
  slice(-nrow(corr1b)) %>%
  dplyr::select(-1)
corr1b

```


## With road type

```{r}
load(here("data/rcommQ.RData"))

corr1 <- dplyr::select(rcommQ, contains("q"), rtype, ID, id3) %>%
  dplyr::select(-qmph) %>%
  pivot_longer(contains("q")) %>%
  mutate(name = substring(name, 8), res = ifelse(substr(name, 1, 1) == "1", "1km", "500m"),
         type = ifelse((substr(name, 4, 4) == "h" | substr(name, 2, 2) == "h"), "Highway", "Local")) %>%
  group_by(rtype, name, value, res, type) %>%
  count() %>%
  mutate(rtype = factor(rtype, levels = c("High/SecHigh", "LocalConn", "Local", "Other")))

rtypecorr <- ggplot(corr1, aes(fill=rtype, y=n, x=value)) + 
    geom_bar(position="fill", stat="identity") +
  xlab("Quartile of road density") +
  ylab("Proportion") +
  scale_fill_colorblind(name = "Road type") +
  facet_wrap(type ~ res) +
  theme(text = element_text(size = 12))

```

## Daily level only (no difference)

```{r}

corr2 <- dplyr::select(rcommLM, daily, awnd,
                       tmax, tmin, RH) %>%
  unique() %>%
  cor()
corrplot(corr2)

data.frame(corr2, var1 = rownames(corr2)) %>%
  pivot_longer(-var1) %>%
  mutate(abscor = abs(value)) %>%
  filter(abscor > 0.5 & abscor < 1) %>% kable(digits = 2)

```

## Trip level only (no difference)

```{r}
corr3 <- dplyr::select(rcommLM, ID, id3, daily, obsdiff, awnd,
                       tmax, tmin, RH) %>%
  unique() %>% select(-id3, -ID) %>%
  cor()
corrplot(corr3)

data.frame(corr3, var1 = rownames(corr3)) %>%
  pivot_longer(-var1) %>%
  mutate(abscor = abs(value)) %>%
  filter(abscor > 0.5 & abscor < 1) %>% kable(digits = 2)

```


# Variability by day of week

```{r}
rcommLM2 <- mutate(rcommLM, dow = wday(date_local))
ggplot(rcommLM2, aes(x = factor(dow), y = lPM)) + geom_boxplot()
```

```{r}

save(corr1b,rtypecorr,  file = here("results/er-reject-res.RData"))
```
