---
title: 'Roadiness: analysis'
author: "Jenna Krall"
date: "10/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
# libraries
library(tidyverse)
library(knitr)
library(here)
library(lme4)
library(broom.mixed)
library(ggthemes)
library(nlme)
library(forcats)
library(patchwork)
library(RColorBrewer)
# library(lmeInfo)

```


```{r}
# load data
load(here("data/rcomm2.RData"))


# load iqrs
load(here("data/iqrs.RData"))

# get functions for models
source(here("functions/model-funs.R"))



```

# Distribution of PM


Meteorology:
- Lag 1: max temp, min temp, wind speed, precipitation
- Lead snow


```{r}
rcomm1 <- rcommLM
```




```{r hists, cache = T}

g1 <- ggplot(rcomm1, aes(x = PM)) + geom_histogram(bins = 20) 
g2 <- ggplot(rcomm1, aes(x = PM)) + geom_boxplot() 
g3 <- ggplot(rcomm1, aes(x = lPM)) + geom_histogram(bins =20) 

g4 <- ggplot(rcomm1, aes(x = lPM)) + geom_boxplot() 

(g1 + g2) /( g3 + g4 )
```


```{r, cache = T}
rcomm1 %>% 
  rename(value = PM) %>%
  summarize(mean = mean(value), sd = sd(value),
            median = median(value), IQR = IQR(value),
            q25 = quantile(value, probs = 0.25), 
            q75 = quantile(value, probs = 0.75),
            min = min(value), max = max(value))
```






# Visualize associations with lPM

```{r, cache = T}

g1 <- ggplot(rcomm1, aes(x = srness, y = lPM)) +
   geom_point() +geom_smooth() 


g2 <- ggplot(rcomm1, aes(x = daily, y = lPM)) +
   geom_point() +geom_smooth() 


g3 <- ggplot(rcomm1, aes(x = obsdiff, y = lPM)) +
   geom_point() +geom_smooth()  + xlab("Hourly diff")

g4 <- ggplot(rcomm1, aes(x = awnd, y = lPM)) +
   geom_point() +geom_smooth() 

g5 <- ggplot(rcomm1, aes(x = tmax, y = lPM)) +
   geom_point() +geom_smooth() 

g6 <- ggplot(rcomm1, aes(x = tmin, y = lPM)) +
   geom_point() +geom_smooth() 

g7 <- ggplot(rcomm1, aes(x = timemin, y = lPM)) +
   geom_point() +geom_smooth() 

g8 <- ggplot(rcomm1, aes(x = mph, y = lPM)) +
   geom_point() +geom_smooth() 

(g1 + g2 + g3 ) / (g4 + g5 + g6 ) 

g7 + g8
```


## Associations with time min

```{r, cache = T}
rcommU1 <- group_by(rcomm1, id3) %>% mutate(mean = mean(lPM), dPM = lPM - mean)
ggplot(rcommU1, aes(x = timemin, y = dPM, group = id3)) + geom_smooth()

```








# Model


```{r}
# Fit AR1 correlation
# groups are big / small


# ID/id3 and ID/id2 are the same: ID/group differs ( does not account for diff trips)
# ID/date/id3, ID/group/id3 are the same, no variation at level 2 (not enough mult trips/day)

# 
rcomm1 <- group_by(rcomm1, ID, id3) %>%
  arrange(rcomm1, timemin) %>%
  ungroup() %>%
  arrange(ID, id3, timemin)
```


## Roadiness 

```{r, cache = T}
eqn1 <- "lPM ~ srness"
res1 <- get_lme(rcomm1, iqrs, eqn1, re = "~ 1| ID / id3")
res1rn <- res1
ACF(res1$lme1, resType = "normalized", maxLag = 30) %>% plot()
 
ggplot(res1$re, aes(x = est, y = name)) + 
  geom_pointrange(aes(xmin = lower, xmax = upper )) +
  xlab("Estimate") + ylab("")

eqn2 <- "lPM ~ srness + awnd + prcpbin + 
               tmax  + tmin +  RH + 
               cat5sm + snowbin" 
res2 <- get_lme(rcomm1, iqrs, eqn2, re = "~ 1| ID / id3")
# ACF(res2$lme1, resType = "normalized", maxLag = 30) %>% plot()

# doesnot run
eqn3 <- "lPM ~ srness + daily  + obsdiff" 
res3 <- get_lme(rcomm1, iqrs, eqn3, re = "~ 1| ID / id3")
# ACF(res3$lme1, resType = "normalized", maxLag = 30) %>% plot()

eqn3b <- "lPM ~ srness + daily" 
res3b <- get_lme(rcomm1, iqrs, eqn3b, re = "~ 1| ID / id3")
# ACF(res3b$lme1, resType = "normalized", maxLag = 30) %>% plot()


eqn4 <- "lPM ~ srness + rushmorn + rusheven" 
res4 <- get_lme(rcomm1, iqrs, eqn4, re = "~ 1| ID / id3")
# ACF(res4$lme1, resType = "normalized", maxLag = 30) %>% plot()

resl <- list(Main = res1,  Meteorology = res2, `Ambient PM2.5` = res3, Rush = res4)
reslrn <- resl
```


```{r}
plot_nocat_sens(resl, "srness")

```





## Road type 

```{r, cache = T}
eqn1 <- "lPM ~ rtype"
res1 <- get_lme(rcomm1, iqrs, eqn1, re = "~ 1| ID / id3")
ACF(res1$lme1, resType = "normalized", maxLag = 30) %>% plot()

ggplot(res1$re, aes(x = est, y = name)) + 
  geom_pointrange(aes(xmin = lower, xmax = upper )) +
  xlab("Estimate") + ylab("")
res1rt <- res1

eqn2 <- "lPM ~ rtype + awnd + prcpbin + 
               tmax  + tmin +  RH + 
               cat5sm + snowbin" 
res2 <- get_lme(rcomm1, iqrs, eqn2, re = "~ 1| ID / id3")
# ACF(res2$lme1, resType = "normalized", maxLag = 30) %>% plot()


eqn3 <- "lPM ~ rtype + daily + obsdiff"
res3 <- get_lme(rcomm1, iqrs, eqn3, re = "~ 1| ID / id3")
# ACF(res3$lme1, resType = "normalized", maxLag = 30) %>% plot()


eqn4 <- "lPM ~ rtype + rushmorn + rusheven" 
res4 <- get_lme(rcomm1, iqrs, eqn4, re = "~ 1| ID / id3")
# ACF(res4$lme1, resType = "normalized", maxLag = 30) %>% plot()

resl <- list(Main = res1,  Meteorology = res2, `Ambient PM2.5` = res3,  Rush = res4)
reslrt <- resl
```


```{r}
fig5 <- plot_cat_sens(reslrt, "rtype")
fig5
```



## Speed 

```{r}
eval1 <- T
```


```{r, eval = eval1, cache = T}
eqn1 <- "lPM ~ mph"
res1 <- get_lme(rcomm1, iqrs, eqn1, re = "~ 1| ID / id3")
res1sp <- res1
ACF(res1$lme1, resType = "normalized", maxLag = 30) %>% plot()
 
ggplot(res1$re, aes(x = est, y = name)) + 
  geom_pointrange(aes(xmin = lower, xmax = upper )) +
  xlab("Estimate") + ylab("")

eqn2 <- "lPM ~ mph + awnd + prcpbin + 
               tmax  + tmin +  RH + 
               cat5sm + snowbin" 
res2 <- get_lme(rcomm1, iqrs, eqn2, re = "~ 1| ID / id3")
# ACF(res2$lme1, resType = "normalized", maxLag = 30) %>% plot()

# doesnot run
eqn3 <- "lPM ~ mph + obsdiff + daily" 
res3 <- get_lme(rcomm1, iqrs, eqn3, re = "~ 1| ID / id3")
# ACF(res3$lme1, resType = "normalized", maxLag = 30) %>% plot()

eqn3b <- "lPM ~ mph + daily" 
res3b <- get_lme(rcomm1, iqrs, eqn3b, re = "~ 1| ID / id3")
# ACF(res3b$lme1, resType = "normalized", maxLag = 30) %>% plot()


eqn4 <- "lPM ~ mph + rushmorn + rusheven" 
res4 <- get_lme(rcomm1, iqrs, eqn4, re = "~ 1| ID / id3")
# ACF(res4$lme1, resType = "normalized", maxLag = 30) %>% plot()

resl <- list(Main = res1, Meteorology = res2, `Ambient PM2.5` = res3, Rush = res4)
```


```{r}
plot_nocat_sens(resl, "mph")

```

```{r}

fig6 <- plot_nocat_sens2(reslrn, "srness", resl, "mph") 
fig6
# g1 + g2+ plot_layout(guides = "collect") & theme(legend.position = 'top')
```




## Speed * Road type

No role

```{r, eval = eval1}
eqn1 <- "lPM ~ mph * rtype"
res1 <- get_lme(rcomm1, iqrs, eqn1, re = "~ 1| ID / id3")
res1$t1 %>% dplyr::select(term, estimate, p.value, conf.low, conf.high) %>%
  dplyr::filter(!is.na(estimate))
# ACF(res1$lme1, resType = "normalized", maxLag = 30) %>% plot()
 

plot_nocat_sens(resl, "mph")

```

## Lags




### Roadiness 

```{r, eval = eval1, cache = T}
rcommlag <- mutate(rcomm1, var = srness)
eqn1 <- "lPM ~ var" 
resl <- runlag(rcommlag, iqrs, eqn1,re = "~ 1| ID / id3", lags = seq(0, 10), corr  = T,
               intervals = T)
SreslRN <- resl
rcomm0 <- rename(rcomm1, var = srness)
eqn1 <- "lPM ~ var"
res1 <- get_lme(rcomm0, iqrs, eqn1, re = "~ 1| ID / id3")
resl[[12]] <- res1
names(resl)[12] <- "main"


```

```{r}
plot_nocat_sens(resl, "var")


```


### Road type


```{r, eval = eval1, cache = T}
rcommlag <- mutate(rcomm1, var = rtype)
eqn1 <- "lPM ~ var" 
resl <- runlag(rcommlag, iqrs, eqn1,re = "~ 1| ID / id3", lags = seq(0, 10), corr  = T,
               intervals = T )
SreslRT <- resl

rcomm0 <- rename(rcomm1, var = rtype)
eqn1 <- "lPM ~ var"
res1 <- get_lme(rcomm0, iqrs, eqn1, re = "~ 1| ID / id3")
resl[[12]] <- res1
names(resl)[12] <- "main"

```


```{r}

figs7 <- plot_cat_senslag(SreslRT, "var")
figs7

```


## Speed

```{r, eval = eval1, cache = T}
rcommlag <- mutate(rcomm1, var = mph)
eqn1 <- "lPM ~ var" 
resl <- runlag(rcommlag, iqrs, eqn1,re = "~ 1| ID / id3", lags = seq(0, 10), corr  = T,
               intervals = T)
SreslS <- resl

rcomm0 <- rename(rcomm1, var = mph)
eqn1 <- "lPM ~ var"
res1 <- get_lme(rcomm0, iqrs, eqn1, re = "~ 1| ID / id3")
resl[[12]] <- res1
names(resl)[12] <- "main"

```

```{r}
plot_nocat_sens(resl, "var")

figs8 <- plot_nocat_senslag(SreslRN, "srness", SreslS, "mph")
figs8
```



## All

```{r, eval = eval1}
eqnA <- "lPM ~ srness + rtype + mph"
resA <- get_lme(rcomm1, iqrs, eqnA, re = "~ 1| ID / id3") 

# still autocorr
acf1 <- ACF(resA$lme1, resType = "normalized", maxLag = 30) 
acf1 %>% plot()
lme1b <- resA$aug
hist(lme1b$.resid)

long <- pivot_longer(lme1b, c(daily, obsdiff, awnd, tmax, tmin, srness, .fitted)) %>%
  filter(name %in% "srness")
ggplot(long, aes(x = value, y = .resid)) +
  geom_point() +
  facet_wrap(~name, scales = "free")


long <- mutate(lme1b, #snowbin = factor(snowbin),
               prcpbin = factor(prcpbin)) %>%
  pivot_longer(c(prcpbin, cat5sm, rtype))  %>% #snowbin, 
  filter(name %in% "rtype")
ggplot(long, aes(x = value, y = .resid)) +
  geom_boxplot() +
  facet_wrap(~name, scales = "free")

```


```{r, eval = F}
resl <- list(Main = res1rt, All = resA)
plot_cat_sens(resl, "rtype")


resl <- list(Main = res1rn, All = resA)
plot_nocat_sens(resl, "srness")

resl <- list(Main = res1sp, All = resA)
plot_nocat_sens(resl, "mph")
```




```{r, eval = eval1}
# Get residuals
save(resA, res1rn, res1rt, res1sp, file = here("results/main-res.RData"))
```











# Misc


## Weather


```{r}
eqn1 <- "lPM ~  awnd + prcpbin + 
               tmax  + tmin +  RH + 
               cat5sm + snowbin"
res <- get_lme(rcomm1, iqrs, eqn1, re = "~ 1| ID / id3") 

plot_cat(res)

```


## Ambient daily and hourly PM

```{r}
eqn1 <- "lPM ~ daily + obsdiff"
res <- get_lme(rcomm1, iqrs, eqn1, re = "~ 1| ID / id3") 

plot_nocat(res)

```


```{r}
save(fig5, fig6, figs7, figs8, file = here("results/lmfig.RData"))
```
