---
title: 'Roadiness: analysis'
author: "Jenna Krall"
date: "10/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, cache = F)
```

```{r}
# libraries
library(tidyverse)
library(knitr)
library(here)
library(lme4)
library(broom.mixed)
library(ggthemes)
library(nlme)
library(forcats)
library(patchwork)
library(RColorBrewer)
library(splines)
# library(lmeInfo)

```


```{r}
# load data
load(here("data/rcomm2.RData"))


# get functions for models
source(here("functions/model-funs.R"))

# load previous results
load(here("data/iqrs.RData"))
load(here("results/main-res.RData"))
base <- res
```



```{r fixbase}
base$t1 <- mutate(base$t1, model = "Main")
base$re <- mutate(base$re, model = "Main")

```
# Sensitivity analysis

```{r adjust}
# Need to remove outliers?
#- Remove PM < 25for models (for normality/skewness)

# remove
shift <- 0.09
rcomm <- filter(rcomm2, PM < 25)  %>% #, PM > 0) 
  mutate(lPM = log(PM + shift),
    cat5sm = fct_relevel(cat5sm, "NW"))


rcomm <- group_by(rcomm, ID, id3) %>%
  arrange(rcomm, timemin) %>%
  ungroup()

# ID 3 is date/commute
rcomm1 <- dplyr::select(rcomm, srness, rtype, id3, PM, daily, 
    obsdiff, ID,date_local, group, awnd , prcpbin , 
    tmax, snowbin, tmin, cat5sm, timemin, lPM) %>% na.omit() 

rcommlag <- dplyr::select(rcomm, srness, rtype, id3, PM, daily, 
    obsdiff, ID,date_local, group, awnd , prcpbin , 
    tmax, snowbin, tmin, cat5sm, timemin, lPM, 
    # lag precip, temp, wind
    prcpbinL1, tmaxL1, tminL1, awndL1, 
    # lead snow
    snowbinL1m,
    # hour mean, hour month mean
    hourly, hourlymonth) %>% na.omit()
```




```{r, eval = F}
baseqn <- "lPM ~ srness + daily + obsdiff + awndL1 + prcpbinL1 + 
               tmaxL1 + tminL1 + rtype + 
               cat5sm + snowbinL1m"

eqn1 <- "lPM ~ srness + daily + obsdiff + awndL1 + prcpbinL1 + 
               tmaxL1 + tminL1 + rtype +
               cat5sm"

eqn2 <- "lPM ~ srness + daily + obsdiff + awnd + prcpbin + 
               tmax + tmin + rtype +  snowbinL1m +
               cat5sm"

eqn3 <-  "lPM ~ srness + daily + obsdiff + awndL1 + prcpbinL1 + 
               tmaxL1 + tminL1 + rtype + 
               cat5sm + snowbinL1m + timemin"


eqn4 <- "lPM ~ srness + daily + obsdiff + awndL1 + prcpbinL1 + 
               tmaxL1 + tminL1 + rtype + snowbinL1m +
               cat5sm + hourly"

eqn5 <- "lPM ~ srness + daily + obsdiff + awndL1 + prcpbinL1 + 
               tmaxL1 + tminL1 + rtype + snowbinL1m +
               cat5sm + hourlymonth"



eqn5 <- "lPM ~ srness + daily + obsdiff + awndL1 + prcpbinL1 + 
               tmaxL1 + tminL1 + rtype + snowbinL1m +
               cat5sm + ns(timemin, 3)"

names <- c("No snow", "Same day met", "Trip time", "Day corr", "Random slope", "No autocor", "Hour mean", "Hour month mean", "Spline time")
eqns <- c(eqn1, eqn2, eqn3, rep(baseeqn, 3), eqn4, eqn5, eqn6)
randeff <- c(rep("~ 1| ID / id3", 3), "~ 1 | ID / group / id3", 
             "~ timemin | ID / id3", rep("~ 1| ID / id3", 4))
ints <- c(T, T, T, F, T, T, T, T, T)
cors <- c(T, T, T, T, T, F, T, T, T)
int1 <- list()

data1 <- rcommlag
for(i in 1 : length(eqns)) {
  print(names[i])
  # if(names[i] %in% c("Lead snow", "Same day met")) {
  #   data1 <- rcommlag
  # } else {
  #   data1 <- rcomm1
  # }
#     lower  est. upper name 
# * <dbl> <dbl> <dbl> <chr>
# 1 0.404 0.423 0.442 sigma
# 2 0.332 0.578 1.01  ID   
# 3 0.491 0.626 0.797 id3  
  res <- get_lme(data1, iqrs, eqns[i], re = randeff[i], intervals = ints[i], corr = cors[i]) 
  t1 <- mutate(res$t1, model = names[i])
  re <- mutate(res$re, model = names[i])

  if(i %in% c(1, 2)) {
    int1[[i]] <- intervals(res$lme1)$fixed
  }
  
  
  if(i == 1 ) {
    resall <- full_join(base$t1, t1)
    varcomp <- full_join(base$re, re)

  } else {
    resall <- full_join(resall, t1)
    varcomp <- full_join(varcomp, re)

  }
}


# reorder
resall <- mutate(resall, model = factor(model, levels = c("Main", names)))
varcomp <- mutate(varcomp, model = factor(model, levels = c("Main", names)))


save(resall, varcomp, file = here("results/sens.RData"))
```







## Plot

```{r}
# load sens results
load(here("results/sens.RData"))

# resall <- filter(resall, model != "Day corr")


```


# Figure SX. Sensitivity analyses for categorical covariates

```{r, fig.height = 10}
plot_catALL(resall)
```


# Figure Sx. Sensitivity analyses for continuous covariates


```{r, fig.height = 10}
plot_nocatALL(resall)
```






## Variance components

**Note: group level produces no variability: remove (no intervals)**

```{r, eval = T}
cols <- rep(brewer.pal(8, "Dark2"), 2)

varcomp <- filter(varcomp, model != "Day corr")

ggplot(varcomp, aes(x = est, y = name)) + 
  geom_pointrange(aes(xmin = lower, xmax = upper, colour = model), 
                  position = position_dodge(0.4)) +
  scale_color_manual(values = cols, name = "Model") +
  xlab("Estimate") + ylab("") +
  facet_wrap(~name, scales = "free") +
  theme_bw() +
  theme(legend.position = "top", text=  element_text(size = 12))

```


